version: '2.1'

services:
  beater-prp:
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && celery -A django_api beat -l ${CELERY_LOG_LEVEL:-info} --scheduler django_celery_beat.schedulers:DatabaseScheduler -b $REDIS_URL"
    image: 'unicef/etools-prp'
    env_file:
      - .env
    depends_on:
      - django_api
      - prp_redis
    restart: always
    volumes:
      - './django_api:/code/'

  worker-prp:
    command: bash -c "/usr/local/bin/waitforit -host=db -port=5432 && celery -A django_api worker -l ${CELERY_LOG_LEVEL:-info} -b $REDIS_URL"
    image: 'unicef/etools-prp'
    env_file:
      - .env
    depends_on:
      - django_api
      - prp_redis
    restart: always
    volumes:
      - './django_api:/code/'

  # ATTENTION: you can either have polymer-built or polymer running.. not both.. always have one commented out
  # to renew the image, go to polymer_3 directory and run the following line:
  # docker build -t unicef/etools-prp-polymer:3latest -f Dockerfile-bundle .
  # if you work on the backend / want to get started quickly, pull latest before running docker-compose up by running:
  # docker pull unicef/etools-prp-polymer:3latest
  polymer:
    image: unicef/etools-prp-polymer:3latest
    volumes: []
    command: "node express.js"
    labels:
      - "traefik.http.routers.polymerB.rule=PathPrefix(`/`)"
      - traefik.http.routers.polymerB.service=polymerB
      - traefik.http.services.polymerB.loadBalancer.server.port=8082
      - traefik.enable=true