apiVersion: batch/v1
kind: Job
metadata:
  name: backend-migration
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
  labels:
    redeploy: "true" 
spec:
  template:
    spec:
      containers:
      - name: backend-migration-container
        image: unicef/etools-prp
        command: ["bash"]
        args: ["-c", "python /code/manage.py makemigrations --merge --noinput && python /code/manage.py migrate"]
        env:
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
            
            - name: DJANGO_DEBUG
              value: "{{DJANGO_DEBUG}}"

            - name: DOMAIN_NAME
              value: {{DOMAIN_NAME}}

            - name: ENV
              value: {{ENV}}

            - name: REDIS_URL
              value: redis://redis:6379/0

            - name: POSTGRES_DB
              value: {{POSTGRES_DB}}
            - name: POSTGRES_HOST
              value: {{POSTGRES_HOST}}
            - name: POSTGRES_USER
              value: {{POSTGRES_USER}}
            - name: POSTGRES_PASSWORD
              value: {{POSTGRES_PASSWORD}}
            - name: EMAIL_HOST_USER
              value: {{EMAIL_HOST_USER}}
            - name: EMAIL_HOST_PASSWORD
              value: {{EMAIL_HOST_PASSWORD}}
            - name: ADMIN_MAIL
              value: {{ADMIN_MAIL}}

            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-access-key-id
                  key: password
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret-access-key
                  key: password
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-storage-bucket-name
                  key: password
            - name: AZURE_B2C_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-client-id
                  key: password
            - name: AZURE_B2C_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-client-secret
                  key: password
            - name: AZURE_B2C_POLICY_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-policy-name
                  key: password
            - name: ELASTIC_APM_DEBUG
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-debug
                  key: password
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-secret-token
                  key: password
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-server-url
                  key: password
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-service-name
                  key: password
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: email-backend
                  key: password
            - name: PMP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pmp-api-password
                  key: password
            - name: PMP_API_USER
              valueFrom:
                secretKeyRef:
                  name: pmp-api-user
                  key: password
            - name: PMP_API_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: pmp-api-endpoint
                  key: password            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: password
      restartPolicy: OnFailure
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: backend-collectstatic
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
  labels:
    redeploy: "true" 
spec:
  template:
    spec:
      containers:
      - name: backend-collectstatic-container
        image: unicef/etools-prp
        command: ["bash"]
        args: ["-c", "python /code/manage.py collectstatic --noinput"]
        volumeMounts:
          - name: static-volume-{{NAMESPACE}}
            mountPath: /data
        env:
            - name: DJANGO_ALLOWED_HOST
              value: {{DJANGO_ALLOWED_HOST}}
            
            - name: DJANGO_DEBUG
              value: "{{DJANGO_DEBUG}}"

            - name: DOMAIN_NAME
              value: {{DOMAIN_NAME}}

            - name: ENV
              value: {{ENV}}

            - name: REDIS_URL
              value: redis://redis:6379/0

            - name: POSTGRES_DB
              value: {{POSTGRES_DB}}
            - name: POSTGRES_HOST
              value: {{POSTGRES_HOST}}
            - name: POSTGRES_USER
              value: {{POSTGRES_USER}}
            - name: POSTGRES_PASSWORD
              value: {{POSTGRES_PASSWORD}}
            - name: EMAIL_HOST_USER
              value: {{EMAIL_HOST_USER}}
            - name: EMAIL_HOST_PASSWORD
              value: {{EMAIL_HOST_PASSWORD}}
            - name: ADMIN_MAIL
              value: {{ADMIN_MAIL}}

            - name: AWS_S3_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-s3-access-key-id
                  key: password
            - name: AWS_S3_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-s3-secret-access-key
                  key: password
            - name: AWS_STORAGE_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: aws-storage-bucket-name
                  key: password
            - name: AZURE_B2C_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-client-id
                  key: password
            - name: AZURE_B2C_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-client-secret
                  key: password
            - name: AZURE_B2C_POLICY_NAME
              valueFrom:
                secretKeyRef:
                  name: azure-b2c-policy-name
                  key: password
            - name: ELASTIC_APM_DEBUG
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-debug
                  key: password
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-secret-token
                  key: password
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-server-url
                  key: password
            - name: ELASTIC_APM_SERVICE_NAME
              valueFrom:
                secretKeyRef:
                  name: elastic-apm-service-name
                  key: password
            - name: EMAIL_BACKEND
              valueFrom:
                secretKeyRef:
                  name: email-backend
                  key: password
            - name: PMP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pmp-api-password
                  key: password
            - name: PMP_API_USER
              valueFrom:
                secretKeyRef:
                  name: pmp-api-user
                  key: password            
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: password
      volumes:
      - name: static-volume-{{NAMESPACE}}
        persistentVolumeClaim:
          claimName: static-volume-claim-{{NAMESPACE}}
      restartPolicy: OnFailure
  backoffLimit: 4