---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devel
  namespace: prp

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devel-user-full-access
  namespace: prp
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs: ["*"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: devel-user-full-access-binding
  namespace: prp
subjects:
- kind: ServiceAccount
  name: devel
  namespace: prp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: devel-user-full-access