---
kind: Service
apiVersion: v1
metadata:
  name: id-management-frontend
  namespace: {{NAMESPACE}}
spec:
  ports:
  - protocol: TCP
    port: 3000
    nodePort: 30050
  type: NodePort
  selector:
    app: id-management-frontend-container
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: id-management-frontend
  labels:
    app: id-management-frontend
  annotations:
    revision: "{{CF_SHORT_REVISION}}"
  namespace: {{NAMESPACE}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: id-management-frontend-container
  template:
    metadata:
      labels:
        app: id-management-frontend-container
    spec:
      containers:
        - name: id-management-frontend
          ports:
            - containerPort: 3000
          image: tivix/etools-prp-id-management-frontend:{{CF_SHORT_REVISION}}
          command: ["bash"]
          args: ["-c", "node node_modules/serve/bin/serve.js -s build"]
